services:
  db:
    image: postgres:16-alpine
    restart: always
    hostname: db
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?err}
      - POSTGRES_DB=${POSTGRES_DB?err}
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  app:
    build: .
    restart: always
    ports:
      - ${HTTP_SERVER_PORT:-8080}:${HTTP_SERVER_PORT:-8080}
    environment:
      - CONFIG_PATH=${CONFIG_PATH?err}
    volumes:
      - ./configs:/configs
      - ./crts:/crts
      - ./docs:/docs
      - ./migrations:/migrations
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg-data:

networks:
  app-network:
    driver: bridge
