openapi: 3.0.3

info:
  title: URL Shortener API
  description: A simple RESTful API that allows users to shorten long URLs.
  contact:
    name: Vadim Barashkov
    email: vadimdominik2005@gmail.com
  license:
    name: MIT
    url: https://opensource.org/license/mit
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Dev and Stage Server
  - url: https://localhost:8443/api/v1
    description: Prod Server

paths:
  /ping:
    get:
      tags:
        - Health
      summary: Ping the server
      description: Returns a pong response to check if the server is running.
      operationId: ping
      responses:
        200:
          description: Success
          content:
            text/plain; charset=utf-8:
              example: pong

  /shorten:
    post:
      tags:
        - URLs
      summary: Shorten a URL
      description: Shortens the given original URL.
      operationId: shortenURL
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/URLRequest"
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/URLResponse"
        400:
          description: Invalid Request Body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /shorten/{shortCode}:
    get:
      tags:
        - URLs
      summary: Resolve a shortened URL
      description: Resolves the short code to the original URL.
      operationId: resolveShortCode
      parameters:
        - $ref: "#/components/parameters/shortCode"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/URLResponse"
        404:
          description: URL Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags:
        - URLs
      summary: Modify a shortened URL
      description: Updates the original URL for the given short code.
      operationId: modifyURL
      parameters:
        - $ref: "#/components/parameters/shortCode"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/URLRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/URLResponse"
        400:
          description: Invalid Request Body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: URL Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags:
        - URLs
      summary: Deactivate a shortened URL
      description: Deactivates the URL associated with the short code.
      operationId: deactivateURL
      parameters:
        - $ref: "#/components/parameters/shortCode"
      responses:
        204:
          description: Success
        404:
          description: URL Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /shorten/{shortCode}/stats:
    get:
      tags:
        - URLs
      summary: Get URL statistics
      description: Retrieves statistics for the URL associated with the short code.
      operationId: getURLStats
      parameters:
        - $ref: "#/components/parameters/shortCode"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/URLStatsResponse"
        404:
          description: URL Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    URLRequest:
      type: object
      required:
        - original_url
      properties:
        original_url:
          type: string
          format: uri
          example: https://example.com
    URLResponse:
      type: object
      required:
        - id
        - short_code
        - original_url
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          format: int64
          example: 1
        short_code:
          type: string
          example: abc123
        original_url:
          type: string
          format: uri
          example: https://example.com
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    URLStats:
      type: object
      required:
        - access_count
      properties:
        access_count:
          type: integer
          format: int64
    URLStatsResponse:
      type: object
      required:
        - id
        - short_code
        - original_url
        - stats
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          format: int64
          example: 1
        short_code:
          type: string
          example: abc123
        original_url:
          type: string
          format: uri
          example: https://example.com
        stats:
          $ref: "#/components/schemas/URLStats"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    ValidationError:
      type: object
      required:
        - field
        - message
      properties:
        field:
          type: string
          example: original_url
        message:
          type: string
          example: invalid url
    ErrorResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          default: error
        message:
          type: string
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"

  parameters:
    shortCode:
      name: shortCode
      in: path
      schema:
        type: string
        example: abc123
      required: true
