name: Dev CI

on:
  push:
    branches:
      - feature/**
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go-version:
          - 1.23.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build binary
        run: go build -v ./...

  lint:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go-version:
          - 1.23.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install linters
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install golang.org/x/lint/golint@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run golint
        run: golint ./...

  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go-version:
          - 1.23.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -v -race -cover ./...
