name: Dev CI

on:
  push:
    branches:
      - feature/**
      - test/**
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go-version:
          - 1.23.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build binary
        run: make build

  lint:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go-version:
          - 1.23.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: --timeout=30m

  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go-version:
          - 1.23.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run unit tests
        run: make test/unit

      - name: Run integration tests
        run: make test/integration
